services:
  database:
    image: mysql:8.4.0
    restart: always
    container_name: database
    environment:
      MYSQL_DATABASE: "starter-kit-db"
      MYSQL_USER: "app_user"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3308:3306"
    volumes:
      - starter_kit_db:/var/lib/mysql
    networks:
      - app_net
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    ports:
      - "80:80"
    restart: unless-stopped
  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "12345678"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
volumes:
  starter_kit_db:
  caddy_data:
  minio_data:
